name: BuildJet Cron Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (UTC)
  workflow_dispatch:

jobs:
  run-converted:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run converted.sh
        run: |
          chmod +x converted.sh
          ./converted.sh
